dirs = [
    'System Volume Information',
    '$RECYCLE.BIN',
    'distributive',
    'downloads',
    '.git',
]

exe = [
    'Console-Launcher',
    'IDLE-Launcher',
    'PyScripter-Launcher',
    'Python-Launcher',
    'PythonW-Launcher64',
    'reamote',
    'crash_reporter',
    'plugin_host-3.3',
    'plugin_host-3.8',
    'subl',
    'update_installer',
    'crashpad_handler',
    'QtWebEngineProcess',
    'CrystalDiskMarkPortable',
    'FastToIcon',
    'FileZillaPortable',
    'IconViewer',
    'MovieThumb',
    'Picasa3',
    'PicasaPhotoViewer',
    'uninstall',
    'qBittorrent',
    'hl2',
    'RUN_HL2',
    'RUN_HL2EP1',
    'RUN_HL2EP2',
    'RUN_HL2LC',
    'launcher',
    'GameOverlayUI',
    'steam',
    'steamerrorreporter',
    'steamerrorreporter64',
    'streaming_client',
    'uninstall',
    'WriteMiniDump',
    'discord',
    'discord-ptb',
    'ferdi-portable',
    'Telegram off',
    'Telegram.',
    'Updater',
    'Telegram',
    'Updater',
    'Telegram',
    'Updater',
    'ViberPortable',
    'DesktopHook64',
    'DTDrop64',
    'KillPot64',
    'PotPlayer64',
    'Восстановить настройки',
    'vlc',
    'FSCapture',
    'FSCrossHair',
    'FSFocus',
    'FSRecorder',
    'Recorder-devices-setup',
    'ShareX',
    'ShareX_NativeMessagingHost',
    'adb',
    'fastboot',
    'aria2c',
    'aria2c',
    'micro',
    'micro',
    'tabby',
    'youtube-dl',
    'AnyDesk',
    'DriverBoosterPortable',
    'IObitUnlockerPortable',
    'kvrt',
    'NTLite',
    'rufus-3.17p',
    'KmdUtil',
    'SandboxieBITS',
    'Win 10 Tweaker',
    'Elevator',
    'WinaeroTweaker',
    'WinaeroTweakerHelper',
    'Windows11DragAndDropToTaskbarFix',
    'WSAToolbox',
]

to_rename = {
    'launcheropera': 'opera'
}
